name: Update Last Commit

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  update-last-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=commit_date::$(date +'%B %d, %Y')"

      - name: Update README
        run: |
          sed -i "s/Last Commit:.*$/Last Commit: \${{ steps.date.outputs.commit_date }}/g" README.md
